/**
 * Generate Embedded Icons Module
 *
 * This script generates a TypeScript module containing all Lucide icons
 * embedded as string constants, so they can be bundled into the plugin.
 */

const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.join(__dirname, '../../external/lucide/icons');
const OUTPUT_FILE = path.join(__dirname, '../src/plugin/icons/lucide-icons.ts');

console.log('Generating embedded icons module...');
console.log('Icons directory:', ICONS_DIR);
console.log('Output file:', OUTPUT_FILE);

// Read all SVG files
const files = fs.readdirSync(ICONS_DIR);
const svgFiles = files.filter(f => f.endsWith('.svg'));

console.log(`Found ${svgFiles.length} icon files`);

// Build the TypeScript module
let output = `/**
 * Lucide Icons - Embedded SVG Data
 *
 * This file is auto-generated by scripts/generate-icons.js
 * DO NOT EDIT MANUALLY
 *
 * Contains ${svgFiles.length} Lucide icons embedded as strings.
 */

export interface LucideIconData {
  name: string;
  svgContent: string;
  categories: string[];
  tags: string[];
}

export const LUCIDE_ICONS: Record<string, LucideIconData> = {
`;

// Process each icon
let count = 0;
for (const svgFile of svgFiles) {
  const iconName = svgFile.replace('.svg', '');
  const svgPath = path.join(ICONS_DIR, svgFile);
  const jsonPath = path.join(ICONS_DIR, `${iconName}.json`);

  // Read SVG content
  const svgContent = fs.readFileSync(svgPath, 'utf8')
    .replace(/\\/g, '\\\\')  // Escape backslashes
    .replace(/`/g, '\\`')     // Escape backticks
    .replace(/\$/g, '\\$')    // Escape dollar signs
    .trim();

  // Read metadata if available
  let categories = [];
  let tags = [];

  if (fs.existsSync(jsonPath)) {
    try {
      const metadata = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
      categories = metadata.categories || [];
      tags = metadata.tags || [];
    } catch (e) {
      console.warn(`Failed to parse metadata for ${iconName}: ${e.message}`);
    }
  }

  // Add to output
  output += `  '${iconName}': {
    name: '${iconName}',
    svgContent: \`${svgContent}\`,
    categories: ${JSON.stringify(categories)},
    tags: ${JSON.stringify(tags)}
  },\n`;

  count++;
  if (count % 100 === 0) {
    console.log(`Processed ${count}/${svgFiles.length} icons...`);
  }
}

output += `};

export const ICON_NAMES = Object.keys(LUCIDE_ICONS);

export function getIcon(name: string): LucideIconData | null {
  return LUCIDE_ICONS[name] || null;
}

export function listIcons(): string[] {
  return ICON_NAMES;
}

export function searchIcons(query: string): string[] {
  const lowerQuery = query.toLowerCase();
  return ICON_NAMES.filter(name =>
    name.toLowerCase().includes(lowerQuery) ||
    LUCIDE_ICONS[name].categories.some(cat => cat.toLowerCase().includes(lowerQuery)) ||
    LUCIDE_ICONS[name].tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
`;

// Write output file
fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

console.log(`✓ Generated ${OUTPUT_FILE}`);
console.log(`✓ Embedded ${count} icons`);
console.log(`✓ File size: ${(fs.statSync(OUTPUT_FILE).size / 1024 / 1024).toFixed(2)} MB`);
console.log('Done!');
